### PR TITLE
Update raphael_defconfig

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by YaroST12** [comment]
Nice.

**Comment by bionicBUG** [comment]
Noice

**Comment by uditkarode** [comment]
Bruh I'm choking wtf is this 😂😂

**Comment by Rasenkai** [comment]
Nice 👍

**Comment by ghost** [comment]
wtf

**Comment by ghost** [comment]
This carelessness is due to the unskilled use of GitHub. Please don't mind。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by melvinstark3** [comment]
Best kernel bro

**Pull request closed without merging**
